exclude_columns = ["arizona_Q1A1",
"arizona_Q2A1_ggr",
"arizona_Q4A1",
"arizona_Q2A1",
"arizona_Q5A1",
"arizona_Q3A1",
"arizona_Q1A2",
"arizona_Q4A2",
"arizona_Q2A2",
"arizona_Q5A2",
"arizona_Q3A2",
"arizona_Q2A2_ggr",
"arizona_Q2A1_mfg",
"arizona_Q2A2_mfg",
"california_Q1A1",
"california_Q4A1",
"california_Q2A1",
"california_Q5A1",
"california_Q3A1",
"colorado_Q1A1",
"colorado_Q2A1_ggr",
"colorado_Q4A1",
"colorado_Q2A1",
"colorado_Q5A1",
"colorado_Q3A1",
"colorado_Q1A2",
"colorado_Q4A2",
"colorado_Q2A2",
"colorado_Q5A2",
"colorado_Q3A2",
"colorado_Q2A2_ggr",
"colorado_Q2A1_mfg",
"colorado_Q2A2_mfg",
"idaho_Q1A1",
"idaho_Q2A1_ggr",
"idaho_Q4A1",
"idaho_Q2A1",
"idaho_Q5A1",
"idaho_Q3A1",
"idaho_Q1A2",
"idaho_Q4A2",
"idaho_Q2A2",
"idaho_Q5A2",
"idaho_Q3A2",
"idaho_Q2A2_ggr",
"idaho_Q2A1_mfg",
"idaho_Q2A2_mfg",
"montana_Q1A1",
"montana_Q2A1_ggr",
"montana_Q4A1",
"montana_Q2A1",
"montana_Q5A1",
"montana_Q3A1",
"montana_Q1A2",
"montana_Q4A2",
"montana_Q2A2",
"montana_Q5A2",
"montana_Q3A2",
"montana_Q2A2_ggr",
"montana_Q2A1_mfg",
"montana_Q2A2_mfg",
"nevada_Q1A1",
"nevada_Q2A1_ggr",
"nevada_Q4A1",
"nevada_Q2A1",
"nevada_Q5A1",
"nevada_Q3A1",
"nevada_Q1A2",
"nevada_Q4A2",
"nevada_Q2A2",
"nevada_Q5A2",
"nevada_Q3A2",
"nevada_Q2A2_ggr",
"nevada_Q2A1_mfg",
"nevada_Q2A2_mfg",
"new mexico_Q1A1",
"new mexico_Q2A1_ggr",
"new mexico_Q4A1",
"new mexico_Q2A1",
"new mexico_Q5A1",
"new mexico_Q3A1",
"new mexico_Q1A2",
"new mexico_Q4A2",
"new mexico_Q2A2",
"new mexico_Q5A2",
"new mexico_Q3A2",
"new mexico_Q2A2_ggr",
"new mexico_Q2A1_mfg",
"new mexico_Q2A2_mfg",
"oregon_Q1A1",
"oregon_Q2A1_ggr",
"oregon_Q4A1",
"oregon_Q2A1",
"oregon_Q5A1",
"oregon_Q3A1",
"oregon_Q1A2",
"oregon_Q4A2",
"oregon_Q2A2",
"oregon_Q5A2",
"oregon_Q3A2",
"oregon_Q2A2_ggr",
"oregon_Q2A1_mfg",
"oregon_Q2A2_mfg",
"texas_Q1A1",
"texas_Q2A1_ggr",
"texas_Q4A1",
"texas_Q2A1",
"texas_Q5A1",
"texas_Q3A1",
"texas_Q1A2",
"texas_Q4A2",
"texas_Q2A2",
"texas_Q5A2",
"texas_Q3A2",
"texas_Q2A2_ggr",
"texas_Q2A1_mfg",
"texas_Q2A2_mfg",
"utah_Q1A1",
"utah_Q2A1_ggr",
"utah_Q4A1",
"utah_Q2A1",
"utah_Q5A1",
"utah_Q3A1",
"utah_Q1A2",
"utah_Q4A2",
"utah_Q2A2",
"utah_Q5A2",
"utah_Q3A2",
"utah_Q2A2_ggr",
"utah_Q2A1_mfg",
"utah_Q2A2_mfg",
"washington_Q1A1",
"washington_Q2A1_ggr",
"washington_Q4A1",
"washington_Q2A1",
"washington_Q5A1",
"washington_Q3A1",
"washington_Q1A2",
"washington_Q4A2",
"washington_Q2A2",
"washington_Q5A2",
"washington_Q3A2",
"washington_Q2A2_ggr",
"washington_Q2A1_mfg",
"washington_Q2A2_mfg",
"wyoming_Q1A1",
"wyoming_Q2A1_ggr",
"wyoming_Q4A1",
"wyoming_Q2A1",
"wyoming_Q5A1",
"wyoming_Q3A1",
"wyoming_Q1A2",
"wyoming_Q4A2",
"wyoming_Q2A2",
"wyoming_Q5A2",
"wyoming_Q3A2",
"wyoming_Q2A2_ggr",
"wyoming_Q2A1_mfg",
"wyoming_Q2A2_mfg",
"california_Q2A1_ggr",
"california_Q1A2",
"california_Q4A2",
"california_Q2A2",
"california_Q5A2",
"california_Q3A2",
"california_Q2A2_ggr",
"california_Q2A1_mfg",
"california_Q2A2_mfg",
"arizona",
"california",
"new.mexico",
"texas",
"washington",
"wyoming",
"oregon",
"montana",
"nevada",
"idaho",
"utah",
"colorado",
"END"]

gpbc_exclude_columns = ['Q1A1',
						'Q1A2',
						'Q2A1',
						'Q2A2',
						'Q3A1',
						'Q3A2',
						'Q4A1',
						'Q4A2',
						'Q5A1',
						'Q5A2',
						'Q6A1',
						'Q6A2',
						'Please enter your Greater Phoenix comments here:',
						'Thank you for taking the survey, clicking " " on this page / will permanently submit your results....'
						]





questions = ['Current $ Personal Income',
			'Retail Sales',
			'Wage & Salary Employment',
			'Population Growth',
			'Single-family Housing Permits',
			'Gross Gaming Revenue',
			'Manufacturing Employment']

column_rename = {'Current $ Personal Income':'Q1',
				'Retail Sales':'Q2',
				'Wage & Salary Employment':'Q3',
				'Population Growth':'Q4',
				'Single-family Housing Permits':'Q5',
				'Gross Gaming Revenue':'Q2_ggr',
				'Manufacturing Employment':'Q2_mfg'}

final_column_rename = {'Q2_ggrA1':'Q2A1_ggr',
						'Q2_ggrA2':'Q2A2_ggr',
						'Q2_mfgA1':'Q2A1_mfg',
						'Q2_mfgA2':'Q2A2_mfg'}

master_column_names = ['Q1A1',
						'Q1A2',
						'Q2A1',
						'Q2A2',
						'Q3A1',
						'Q3A2',
						'Q4A1',
						'Q4A2',
						'Q5A1',
						'Q5A2',
						'Q2A1_mfg',
						'Q2A2_mfg',
						'Q2A1_ggr',
						'Q2A2_ggr']

import_panel_rename = {'Email' : 'PrimaryEmail',
						'Q1A1arizona' : 'arizona_Q1A1',
						'Q1A2arizona' : 'arizona_Q1A2',
						'Q2A1arizona' : 'arizona_Q2A1',
						'Q2A2arizona' : 'arizona_Q2A2',
						'Q3A1arizona' : 'arizona_Q3A1',
						'Q3A2arizona' : 'arizona_Q3A2',
						'Q4A1arizona' : 'arizona_Q4A1',
						'Q4A2arizona' : 'arizona_Q4A2',
						'Q5A1arizona' : 'arizona_Q5A1',
						'Q5A2arizona' : 'arizona_Q5A2',
						'Q2A1_mfgarizona' : 'arizona_Q2A1_mfg',
						'Q2A2_mfgarizona' : 'arizona_Q2A2_mfg',
						'Q2A1_ggrarizona' : 'arizona_Q2A1_ggr',
						'Q2A2_ggrarizona' : 'arizona_Q2A2_ggr',
						'Q1A1california' : 'california_Q1A1',
						'Q1A2california' : 'california_Q1A2',
						'Q2A1california' : 'california_Q2A1',
						'Q2A2california' : 'california_Q2A2',
						'Q3A1california' : 'california_Q3A1',
						'Q3A2california' : 'california_Q3A2',
						'Q4A1california' : 'california_Q4A1',
						'Q4A2california' : 'california_Q4A2',
						'Q5A1california' : 'california_Q5A1',
						'Q5A2california' : 'california_Q5A2',
						'Q2A1_mfgcalifornia' : 'california_Q2A1_mfg',
						'Q2A2_mfgcalifornia' : 'california_Q2A2_mfg',
						'Q2A1_ggrcalifornia' : 'california_Q2A1_ggr',
						'Q2A2_ggrcalifornia' : 'california_Q2A2_ggr',
						'Q1A1colorado' : 'colorado_Q1A1',
						'Q1A2colorado' : 'colorado_Q1A2',
						'Q2A1colorado' : 'colorado_Q2A1',
						'Q2A2colorado' : 'colorado_Q2A2',
						'Q3A1colorado' : 'colorado_Q3A1',
						'Q3A2colorado' : 'colorado_Q3A2',
						'Q4A1colorado' : 'colorado_Q4A1',
						'Q4A2colorado' : 'colorado_Q4A2',
						'Q5A1colorado' : 'colorado_Q5A1',
						'Q5A2colorado' : 'colorado_Q5A2',
						'Q2A1_mfgcolorado' : 'colorado_Q2A1_mfg',
						'Q2A2_mfgcolorado' : 'colorado_Q2A2_mfg',
						'Q2A1_ggrcolorado' : 'colorado_Q2A1_ggr',
						'Q2A2_ggrcolorado' : 'colorado_Q2A2_ggr',
						'Q1A1idaho' : 'idaho_Q1A1',
						'Q1A2idaho' : 'idaho_Q1A2',
						'Q2A1idaho' : 'idaho_Q2A1',
						'Q2A2idaho' : 'idaho_Q2A2',
						'Q3A1idaho' : 'idaho_Q3A1',
						'Q3A2idaho' : 'idaho_Q3A2',
						'Q4A1idaho' : 'idaho_Q4A1',
						'Q4A2idaho' : 'idaho_Q4A2',
						'Q5A1idaho' : 'idaho_Q5A1',
						'Q5A2idaho' : 'idaho_Q5A2',
						'Q2A1_mfgidaho' : 'idaho_Q2A1_mfg',
						'Q2A2_mfgidaho' : 'idaho_Q2A2_mfg',
						'Q2A1_ggridaho' : 'idaho_Q2A1_ggr',
						'Q2A2_ggridaho' : 'idaho_Q2A2_ggr',
						'Q1A1montana' : 'montana_Q1A1',
						'Q1A2montana' : 'montana_Q1A2',
						'Q2A1montana' : 'montana_Q2A1',
						'Q2A2montana' : 'montana_Q2A2',
						'Q3A1montana' : 'montana_Q3A1',
						'Q3A2montana' : 'montana_Q3A2',
						'Q4A1montana' : 'montana_Q4A1',
						'Q4A2montana' : 'montana_Q4A2',
						'Q5A1montana' : 'montana_Q5A1',
						'Q5A2montana' : 'montana_Q5A2',
						'Q2A1_mfgmontana' : 'montana_Q2A1_mfg',
						'Q2A2_mfgmontana' : 'montana_Q2A2_mfg',
						'Q2A1_ggrmontana' : 'montana_Q2A1_ggr',
						'Q2A2_ggrmontana' : 'montana_Q2A2_ggr',
						'Q1A1nevada' : 'nevada_Q1A1',
						'Q1A2nevada' : 'nevada_Q1A2',
						'Q2A1nevada' : 'nevada_Q2A1',
						'Q2A2nevada' : 'nevada_Q2A2',
						'Q3A1nevada' : 'nevada_Q3A1',
						'Q3A2nevada' : 'nevada_Q3A2',
						'Q4A1nevada' : 'nevada_Q4A1',
						'Q4A2nevada' : 'nevada_Q4A2',
						'Q5A1nevada' : 'nevada_Q5A1',
						'Q5A2nevada' : 'nevada_Q5A2',
						'Q2A1_mfgnevada' : 'nevada_Q2A1_mfg',
						'Q2A2_mfgnevada' : 'nevada_Q2A2_mfg',
						'Q2A1_ggrnevada' : 'nevada_Q2A1_ggr',
						'Q2A2_ggrnevada' : 'nevada_Q2A2_ggr',
						'Q1A1new mexico' : 'new mexico_Q1A1',
						'Q1A2new mexico' : 'new mexico_Q1A2',
						'Q2A1new mexico' : 'new mexico_Q2A1',
						'Q2A2new mexico' : 'new mexico_Q2A2',
						'Q3A1new mexico' : 'new mexico_Q3A1',
						'Q3A2new mexico' : 'new mexico_Q3A2',
						'Q4A1new mexico' : 'new mexico_Q4A1',
						'Q4A2new mexico' : 'new mexico_Q4A2',
						'Q5A1new mexico' : 'new mexico_Q5A1',
						'Q5A2new mexico' : 'new mexico_Q5A2',
						'Q2A1_mfgnew mexico' : 'new mexico_Q2A1_mfg',
						'Q2A2_mfgnew mexico' : 'new mexico_Q2A2_mfg',
						'Q2A1_ggrnew mexico' : 'new mexico_Q2A1_ggr',
						'Q2A2_ggrnew mexico' : 'new mexico_Q2A2_ggr',
						'Q1A1oregon' : 'oregon_Q1A1',
						'Q1A2oregon' : 'oregon_Q1A2',
						'Q2A1oregon' : 'oregon_Q2A1',
						'Q2A2oregon' : 'oregon_Q2A2',
						'Q3A1oregon' : 'oregon_Q3A1',
						'Q3A2oregon' : 'oregon_Q3A2',
						'Q4A1oregon' : 'oregon_Q4A1',
						'Q4A2oregon' : 'oregon_Q4A2',
						'Q5A1oregon' : 'oregon_Q5A1',
						'Q5A2oregon' : 'oregon_Q5A2',
						'Q2A1_mfgoregon' : 'oregon_Q2A1_mfg',
						'Q2A2_mfgoregon' : 'oregon_Q2A2_mfg',
						'Q2A1_ggroregon' : 'oregon_Q2A1_ggr',
						'Q2A2_ggroregon' : 'oregon_Q2A2_ggr',
						'Q1A1texas' : 'texas_Q1A1',
						'Q1A2texas' : 'texas_Q1A2',
						'Q2A1texas' : 'texas_Q2A1',
						'Q2A2texas' : 'texas_Q2A2',
						'Q3A1texas' : 'texas_Q3A1',
						'Q3A2texas' : 'texas_Q3A2',
						'Q4A1texas' : 'texas_Q4A1',
						'Q4A2texas' : 'texas_Q4A2',
						'Q5A1texas' : 'texas_Q5A1',
						'Q5A2texas' : 'texas_Q5A2',
						'Q2A1_mfgtexas' : 'texas_Q2A1_mfg',
						'Q2A2_mfgtexas' : 'texas_Q2A2_mfg',
						'Q2A1_ggrtexas' : 'texas_Q2A1_ggr',
						'Q2A2_ggrtexas' : 'texas_Q2A2_ggr',
						'Q1A1utah' : 'utah_Q1A1',
						'Q1A2utah' : 'utah_Q1A2',
						'Q2A1utah' : 'utah_Q2A1',
						'Q2A2utah' : 'utah_Q2A2',
						'Q3A1utah' : 'utah_Q3A1',
						'Q3A2utah' : 'utah_Q3A2',
						'Q4A1utah' : 'utah_Q4A1',
						'Q4A2utah' : 'utah_Q4A2',
						'Q5A1utah' : 'utah_Q5A1',
						'Q5A2utah' : 'utah_Q5A2',
						'Q2A1_mfgutah' : 'utah_Q2A1_mfg',
						'Q2A2_mfgutah' : 'utah_Q2A2_mfg',
						'Q2A1_ggrutah' : 'utah_Q2A1_ggr',
						'Q2A2_ggrutah' : 'utah_Q2A2_ggr',
						'Q1A1washington' : 'washington_Q1A1',
						'Q1A2washington' : 'washington_Q1A2',
						'Q2A1washington' : 'washington_Q2A1',
						'Q2A2washington' : 'washington_Q2A2',
						'Q3A1washington' : 'washington_Q3A1',
						'Q3A2washington' : 'washington_Q3A2',
						'Q4A1washington' : 'washington_Q4A1',
						'Q4A2washington' : 'washington_Q4A2',
						'Q5A1washington' : 'washington_Q5A1',
						'Q5A2washington' : 'washington_Q5A2',
						'Q2A1_mfgwashington' : 'washington_Q2A1_mfg',
						'Q2A2_mfgwashington' : 'washington_Q2A2_mfg',
						'Q2A1_ggrwashington' : 'washington_Q2A1_ggr',
						'Q2A2_ggrwashington' : 'washington_Q2A2_ggr',
						'Q1A1wyoming' : 'wyoming_Q1A1',
						'Q1A2wyoming' : 'wyoming_Q1A2',
						'Q2A1wyoming' : 'wyoming_Q2A1',
						'Q2A2wyoming' : 'wyoming_Q2A2',
						'Q3A1wyoming' : 'wyoming_Q3A1',
						'Q3A2wyoming' : 'wyoming_Q3A2',
						'Q4A1wyoming' : 'wyoming_Q4A1',
						'Q4A2wyoming' : 'wyoming_Q4A2',
						'Q5A1wyoming' : 'wyoming_Q5A1',
						'Q5A2wyoming' : 'wyoming_Q5A2',
						'Q2A1_mfgwyoming' : 'wyoming_Q2A1_mfg',
						'Q2A2_mfgwyoming' : 'wyoming_Q2A2_mfg',
						'Q2A1_ggrwyoming' : 'wyoming_Q2A1_ggr',
						'Q2A2_ggrwyoming' : 'wyoming_Q2A2_ggr'}
