insert into wbc_archive_load  Select Organization, States, 
format(Q1A1,1), 
format(Q2A1,1),
format(Q3A1,1), 
format(Q4A1,1), 
format(Q5A1,1), 
format(Q1A2,1), 
format(Q2A2,1), 
format(Q3A2,1), 
format(Q4A2,1), 
format(Q5A2,1), 
format(Q2A1_ggr,1), 
format(Q2A2_ggr,1), 
format(Q2A1_mfg,1), 
format(Q2A2_mfg,1), 
date from load_table_new;

delete from load_table_new;

delete from wbc_deployment;

insert into wbc_deployment select States, Organization, 
format(Q1A1,1),  
format(Q2A1_ggr,1),  
format(Q4A1,1),  
format(Q2A1,1),  
format(Q5A1,1),  
format(Q3A1,1),  
format(Q1A2,1),  
format(Q2A2_ggr,1),  
format(Q4A2,1),  
format(Q2A2,1),  
format(Q5A2,1),  
format(Q3A2,1),  
format(Q2A1_mfg,1),  
format(Q2A2_mfg,1),  
max(date) from wbc_archive_load group by Organization, States; 

insert into wbc_deployment select States, 'Consensus', 
format(avg(Q1A1),1),
format(avg(Q2A1_ggr),1), 
format(avg(Q4A1),1), 
format(avg(Q2A1),1), 
format(avg(Q5A1),1), 
format(avg(Q3A1),1), 
format(avg(Q1A2),1), 
format(avg(Q2A2_ggr),1), 
format(avg(Q4A2),1), 
format(avg(Q2A2),1), 
format(avg(Q5A2),1), 
format(avg(Q3A2),1), 
format(avg(Q2A1_mfg),1), 
format(avg(Q2A2_mfg),1), date from wbc_archive_load where month(date) = month(now()) and year(date) = year(now()) group by States;


insert into wbc_deployment select States, 'Last Month Consensus', 
format(avg(Q1A1),1), 
format(avg(Q2A1_ggr),1), 
format(avg(Q4A1),1), 
format(avg(Q2A1),1), 
format(avg(Q5A1),1), 
format(avg(Q3A1),1), 
format(avg(Q1A2),1), 
format(avg(Q2A2_ggr),1), 
format(avg(Q4A2),1), 
format(avg(Q2A2),1), 
format(avg(Q5A2),1), 
format(avg(Q3A2),1), 
format(avg(Q2A1_mfg),1), 
format(avg(Q2A2_mfg),1), date from wbc_archive_load where month(date) = (month(now()) - 1) and year(date) = year(now()) group by States;
